### ISSUE TITLE
fixes for README

### ISSUE THREAD

**Issue by ayechief** [aj47/techfren-vids#2]
I'll bold correct values: 

14. place the file from 13 in your controlnet folder like this: C:\Users<YOUR USERNAME>\pinokio\api\comfyui.git\app\models\controlnet **\instantid** (you can find the files folder from pinokio by clicking the files 

18. place the file from step **15** in your lora folder like: C:\Users<YOUR USERNAME>\pinokio\api\comfyui.git\app\models\loras

so in 14. you need to place files in C:\...\controlnet\instantid - otherwise it will download the model again because it'll say it doesn't see it
in 18. it's file from step 15, not 16

**Comment by aj47** [comment]
Thanks @ayechief ! can you confirm these changes: https://github.com/aj47/techfren-vids/commit/7111a4d54c8d18f753dcc06bded14ec708e0e8e4 or did i miss something
